# Generated by Django 5.0.6 on 2024-07-09 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_core', '0002_alter_comment_author_alter_image_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog_core.post'),
            preserve_default=False,
        ),
    ]
